apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-reader-${SPOKE_NAME}
  namespace: ${SPOKE_NAME}
---
apiVersion: v1
kind: Secret
metadata:
  name: eso-token-${SPOKE_NAME}
  namespace: ${SPOKE_NAME}
  annotations:
    kubernetes.io/service-account.name: eso-reader-${SPOKE_NAME}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-cert-reader-${SPOKE_NAME}
  namespace: ${SPOKE_NAME}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-reader-binding-${SPOKE_NAME}
  namespace: ${SPOKE_NAME}
subjects:
  - kind: ServiceAccount
    name: eso-reader-${SPOKE_NAME}
    namespace: ${SPOKE_NAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-cert-reader-${SPOKE_NAME}
