apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-agent-params
  namespace: argocd
data:
  principal.listen.host: ""
  principal.allowed-namespaces: "*"
  principal.tls.client-cert.require: "true"
  principal.tls.client-cert.match-subject: "true"
  principal.tls.server.root-ca-secret-name: argocd-agent-ca
  principal.resource-proxy.ca.secret-name: argocd-agent-ca
  principal.auth: "mtls:subject:CN=([^,]+)"
  principal.jwt.allow-generate: "true"
