apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hub-cluster-dev
  source:
    repoURL: https://github.com/my-org/platform-repo.git
    targetRevision: main
    path: platform-configs/hub-cluster/apps/microservices-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
