apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
  # Pull base manifests directly from upstream Google Cloud microservices-demo repository
  - github.com/GoogleCloudPlatform/microservices-demo/kustomize/base?ref=v0.10.1
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kubara-argocd
      environment: dev

# Customize images or apply patches if needed
images:
  - name: frontend
    newName: gcr.io/google-samples/microservices-demo/frontend
    newTag: v0.10.1
